### ISSUE TITLE
basename support?

### ISSUE THREAD

**Issue by nicholasareed** [nheyn/react-stack-skeleton#1]
Great skeleton app! I was trying to get it working with a basename (multiple apps on different subdirectories), but I can't seem to figure out how to get past the `Invariant Violation: Browser history needs a DOM` errors that result when I try to initiate using the recommend v3 way: 

```
import { useRouterHistory } from 'react-router'
import { createHistory } from 'history'

const history = useRouterHistory(createHistory)({
  basename: '/base-path'
})
```

Do you know how this could be done?

**Comment by nheyn** [comment]
Because of the major changes between v3 and v4 of react-router, I have had to deprecate express-react-router (which is where this would need to take place). For more info on server side routing in v4, see https://reacttraining.com/react-router/web/guides/server-rendering.

Sorry for the delay in answering.
